""""""


class PingApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client):
        self.api_client = api_client

    def ping(self) -> str:
        """Check if the API is alive"""
        raise NotImplementedError
        # return self.api_client.query_element(element_name='ping')
